language: php

php:
    - 5.2
    - 5.3
    - 5.4

env:
    - WP_VERSION=4.0.5
    - WP_VERSION=4.1.5
    - WP_VERSION=4.2.2

before_script:
    - wget https://raw.github.com/wp-cli/sample-plugin/master/bin/install-wp-tests.sh
    - export WP_TESTS_DIR=wordpress
    - bash install-wp-tests.sh wordpress root '' localhost $WP_VERSION
    - cd wordpress

script:
    - phpunit -c ../tests/unit/ --exclude-group invalid

notifications:
    email:
        on_success: never
        on_failure: always
